title: Ana María Sosa | Web Citizen
email: anamariasosam@gmail.com
description: Aprendí que todo lo que me enseñan lo debo compartir y no hay mejor forma que un blog para hacerlo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anamariasosa.com" # the base hostname & protocol for your site
twitter_username: anamariasosam
github_username:  anamariasosa
avatar: http://anamariasosa.com/img/blog.png
paginate: 3
locale: en_us
nav_list:
  Home : ['Inicio', '/', 'fa-home']
  About : ['About', '/about', 'fa-diamond']
  Coding : ['Coding', '/category/coding/', 'fa-code']

single_footer: '<p> Made with <i class="fa fa-heart"></i> | Hosted by Github. | 2017 © </p>'

permalink: /:title
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock

jekyll-mentions: https://twitter.com

livereload: true

sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true
      feature_image: recommend-woods
      author_url: "http://anamariasosa.me"
      author_name: "Ana Sosa"
      read_time: 3
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
