# Site settings
title: Made In Spanish
subtitle: With Love
email: madeinspanishwithlove@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://madeinspanish.github.io" # the base hostname & protocol for your site
city: Medell√≠n
country: Colombia
phone: (+57) 3155533098

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
github_url: https://github.com/MadeInSpanish
instagram_url: https://instagram.com/madeinspanish
twitter_url: https://twitter.com/madein_spanish

# Build settings
markdown: kramdown
permalink: /:title
